[package]
name = "ryter-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Ratatui frontend for Ryter"

[dependencies]
ryter-core.workspace = true
ratatui.workspace = true
crossterm.workspace = true
tokio.workspace = true
toml.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
